"""Initial schema: eval_runs, eval_cases, pipeline_documents

Revision ID: 001_initial_schema
Revises: 
Create Date: 2024-01-01 00:00:00.000000

WHY EXPLICIT MIGRATION (not autogenerate):
Hand-writing the first migration ensures:
1. Correct PostgreSQL-specific types (JSONB not JSON, ARRAY not TEXT)
2. Proper indexes on query-hot columns
3. Comments on columns (for future DBA clarity)
4. Explicit constraint names (easier to drop/modify later)
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers
revision = "001_initial_schema"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ── eval_runs ─────────────────────────────────────────────────────────────
    op.create_table(
        "eval_runs",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
            comment="Primary key — generated by PostgreSQL pgcrypto extension",
        ),
        sa.Column(
            "version_tag",
            sa.VARCHAR(100),
            nullable=False,
            comment="Semantic version of the pipeline (e.g., v1.0.0-mmr)",
        ),
        sa.Column("pipeline_name", sa.VARCHAR(200), nullable=False),
        sa.Column(
            "status",
            sa.VARCHAR(20),
            nullable=False,
            server_default="pending",
            comment="pending | running | completed | failed",
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
        ),
        sa.Column("completed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("total_cases", sa.Integer(), nullable=False, server_default="0"),
        # RAGAS aggregate scores — NULL until eval completes
        sa.Column("avg_faithfulness", sa.Float(), nullable=True),
        sa.Column("avg_answer_relevancy", sa.Float(), nullable=True),
        sa.Column("avg_context_precision", sa.Float(), nullable=True),
        sa.Column("avg_context_recall", sa.Float(), nullable=True),
        # JSONB for pipeline config snapshot — queryable, indexable
        sa.Column(
            "run_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default="{}",
        ),
        sa.Column("error_message", sa.Text(), nullable=True),
    )

    # Index on version_tag: common query pattern is "show me all runs for v1.x"
    op.create_index("ix_eval_runs_version_tag", "eval_runs", ["version_tag"])
    op.create_index("ix_eval_runs_created_at", "eval_runs", ["created_at"])
    op.create_index("ix_eval_runs_status", "eval_runs", ["status"])

    # GIN index on JSONB metadata — enables fast queries like:
    # WHERE run_metadata @> '{"chunk_size": 512}'
    op.create_index(
        "ix_eval_runs_metadata_gin",
        "eval_runs",
        ["run_metadata"],
        postgresql_using="gin",
    )

    # ── eval_cases ────────────────────────────────────────────────────────────
    op.create_table(
        "eval_cases",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "eval_run_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("eval_runs.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("answer", sa.Text(), nullable=False),
        # PostgreSQL ARRAY: efficient for ordered list of retrieved chunks
        sa.Column(
            "contexts",
            postgresql.ARRAY(sa.Text()),
            nullable=False,
            server_default="{}",
        ),
        sa.Column("ground_truth", sa.Text(), nullable=False),
        # Per-case RAGAS metric scores — nullable (metric may fail for specific cases)
        sa.Column("faithfulness_score", sa.Float(), nullable=True),
        sa.Column("answer_relevancy_score", sa.Float(), nullable=True),
        sa.Column("context_precision_score", sa.Float(), nullable=True),
        sa.Column("context_recall_score", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
        ),
    )

    # Index on eval_run_id: primary access pattern is "get all cases for run X"
    op.create_index("ix_eval_cases_eval_run_id", "eval_cases", ["eval_run_id"])
    op.create_index("ix_eval_cases_created_at", "eval_cases", ["created_at"])

    # ── pipeline_documents ────────────────────────────────────────────────────
    op.create_table(
        "pipeline_documents",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "doc_id",
            sa.VARCHAR(500),
            nullable=False,
            comment="ID used in ChromaDB — SHA256 hash of filename + content prefix",
        ),
        sa.Column("filename", sa.VARCHAR(500), nullable=False),
        sa.Column("chunk_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column(
            "ingested_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
        ),
        sa.Column("collection_name", sa.VARCHAR(200), nullable=False),
        sa.Column(
            "doc_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default="{}",
        ),
        # Unique constraint: same doc can't be in same collection twice
        sa.UniqueConstraint("doc_id", "collection_name", name="uq_doc_collection"),
    )

    op.create_index(
        "ix_pipeline_documents_collection",
        "pipeline_documents",
        ["collection_name"],
    )


def downgrade() -> None:
    op.drop_table("eval_cases")
    op.drop_table("eval_runs")
    op.drop_table("pipeline_documents")
